### ISSUE TITLE
TypeError: Cannot read properties of undefined

### ISSUE THREAD

**Issue by Bernd9000** [eifel-tech/ioBroker.cloudless-homeconnect#107]
Habe zwei  Geräte:
1.) Bosch Waschmaschine WGB244040/11     (cloudless-homeconnect.0.484010534615005556)
2.) Bosch Geschirrspüler  SMD6TCX00E/17     (IOB Eintrag nicht vorhanden)

Dateien sind nur die von der Waschmaschine vorhanden:
484010534615005556_DeviceDescription.xml
484010534615005556_FeatureMapping.xml

IOB Log:

cloudless-homeconnect.0 | 2024-09-23 16:22:00.664 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
cloudless-homeconnect.0 | 2024-09-23 16:22:00.663 | info | terminating
cloudless-homeconnect.0 | 2024-09-23 16:22:00.659 | error | Cannot read properties of undefined (reading 'filter')
cloudless-homeconnect.0 | 2024-09-23 16:22:00.659 | error | TypeError: Cannot read properties of undefined (reading 'filter')     at joinFeature (C:\Software\ioBroker\node_modules\iobroker.cloudless-homeconnect\js\Xml2JsonConverter.js:18:4)     at C:\Software\ioBroker\node_modules\iobroker.cloudless-homeconnect\js\Xml2JsonConverter.js:172:4     at Array.forEach (<anonymous>)     at Object.xml2json (C:\Software\ioBroker\node_modules\iobroker.cloudless-homeconnect\js\Xml2JsonConverter.js:171:62)     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)     at async CloudlessHomeconnect.loadConfig (C:\Software\ioBroker\node_modules\iobroker.cloudless-homeconnect\main.js:388:23)     at async CloudlessHomeconnect.onReady (C:\Software\ioBroker\node_modules\iobroker.cloudless-homeconnect\main.js:89:25)
cloudless-homeconnect.0 | 2024-09-23 16:22:00.659 | error | unhandled promise rejection: Cannot read properties of undefined (reading 'filter')
cloudless-homeconnect.0 | 2024-09-23 16:22:00.658 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
cloudless-homeconnect.0 | 2024-09-23 16:22:00.446 | info | Found file: 484010534615005556_FeatureMapping.xml
cloudless-homeconnect.0 | 2024-09-23 16:22:00.441 | info | Found file: 484010534615005556_DeviceDescription.xml
cloudless-homeconnect.0 | 2024-09-23 16:22:00.346 | info | Found 2 device(s).
cloudless-homeconnect.0 | 2024-09-23 16:21:59.662 | info | Login sucessfull. Trying to catch token...

**Comment by eifel-tech** [comment]
Kannst du mir die beiden Dateien zur Verfügung stellen? Die werden nicht richtig geparst, deswegen wird nach einem Gerät schon abgebrochen...

**Comment by Bernd9000** [comment]
[Dateien.zip](https://github.com/user-attachments/files/17099295/Dateien.zip)

**Comment by eifel-tech** [comment]
Bitte nochmal neu installieren und probieren. Zumindest das eine Gerät sollte jetzt die Konfig erstellen können.

**Comment by Bernd9000** [comment]
Super, das ging ja schnell, vielen Dank

Hab nur noch eine Warnung im IOB Log mit dem PowerState
Und was komisch ist, die folgenden Dateien vom Geschirrspüler sind gar nicht vorhanden:
012090527895006154_FeatureMapping.xml
012090527895006154_DeviceDescription.xml
Aber IOB Datenpunkte wurden gefüllt.

cloudless-homeconnect.0 | 2024-09-23 17:09:43.383 | warn | State value to set for "cloudless-homeconnect.0.484010534615005556.Setting.PowerState" has value "0" less than min "1"
cloudless-homeconnect.0 | 2024-09-23 17:09:42.857 | info | Found file: 012090527895006154_FeatureMapping.xml
cloudless-homeconnect.0 | 2024-09-23 17:09:42.856 | info | Found file: 012090527895006154_DeviceDescription.xml
cloudless-homeconnect.0 | 2024-09-23 17:09:42.543 | info | Found file: 484010534615005556_FeatureMapping.xml
cloudless-homeconnect.0 | 2024-09-23 17:09:42.539 | info | Found file: 484010534615005556_DeviceDescription.xml
cloudless-homeconnect.0 | 2024-09-23 17:09:42.460 | info | Found 2 device(s).
cloudless-homeconnect.0 | 2024-09-23 17:09:41.883 | info | Login sucessfull. Trying to catch token...
cloudless-homeconnect.0 | 2024-09-23 17:09:40.363 | info | starting.  Version 1.1.0 (non-npm:  eifel-tech/ioBroker.cloudless-homeconnect#fa0a5ce513c7116d3edc6cf95cde19241b9a6398)  in C:/Software/ioBroker/node_modules/iobroker.cloudless-homeconnect,  node: v20.17.0, js-controller: 6.0.11
