### ISSUE TITLE
Vorschlag: Gerät deaktivieren

### ISSUE THREAD

**Issue by Bernd9000** [eifel-tech/ioBroker.cloudless-homeconnect#117]
Wunsch:
Bei mehreren Geräten die Möglichkeit schaffen per Datenpunkt im IOB dieses für den Adapter zu deaktivieren.
Das ist z.B. für die Fehlersuche interessant um sich nur auf ein Gerät zu konzentrieren.

**Comment by eifel-tech** [comment]
Es gibt jetzt den DP `observe`. Mit `false` kann damit ein Gerät deaktiviert werden. Damit das richtig funktioniert, muss aber der Adapter nach der Installation gestoppt werden, den Objektbaum `General` löschen und den Inhalt von `info.config` löschen, damit die Konfiguration neu abgerufen wird. Danach Adapter neu starten. Evtl. noch `host` in `info.config` ersetzen und nochmal neu starten, wenn die Verbindung nicht hergestellt werden kann. Vgl. Readme.

**Comment by Bernd9000** [comment]
Danke, funktioniert
