### ISSUE TITLE
Frage: Manuell eingestellte Optionen Typ "Washer"

### ISSUE THREAD

**Issue by Bernd9000** [eifel-tech/ioBroker.cloudless-homeconnect#118]
Wird direkt bei der Waschmaschine  ein Waschprogramm gewählt wird dies unter folgendem IOB Pfad angezeigt:
`cloudless-homeconnect.0.484010534615005556.SelectedProgram`

Allerdings nicht die veränderten Optionen z.B. Drehzahl und Temperatur.
Ändere ich z.B. direkt an der Maschine die Temperatur beim Waschprogramm "Cotton_Cotton_Cotton" ändert sich dieser IOB Datenpunkt nicht:
`cloudless-homeconnect.0.484010534615005556.Program.Cotton_Cotton_Cotton.Temperature`

Kann man die eingestellten Optionen zur Verfügung zu stellen ?

**Comment by eifel-tech** [comment]
Nein, leider nicht. Der Adapter fragt jede Minute nach allen aktuellen Werten: `/ro/allMandatoryValues` Wenn die Optionen dabei nicht übermittelt werden, stellt das Gerät diese auch nicht zur Verfügung :-(
