### ISSUE TITLE
AggregateError

### ISSUE THREAD

**Issue by Bernd9000** [eifel-tech/ioBroker.cloudless-homeconnect#123]
Wie [hier](https://github.com/eifel-tech/ioBroker.cloudless-homeconnect/issues/108#issuecomment-2396847801) versprochen die neue Fehlermeldung.
Der Fehler tritt dann auf wenn das Gerät nicht mehr im WLAN vorhanden ist.
Der Adapter wird dann beendet und später wegen "Restart lopp detected" stillgelegt durch IOB.

IOB Info Log:

cloudless-homeconnect.0 | 2024-10-15 00:08:08.763 | info | terminating
-- | -- | -- | --
cloudless-homeconnect.0 | 2024-10-15 00:08:08.256 | error | Connection error for device 012090527895006154: Error: WebSocket was closed before the connection was established
cloudless-homeconnect.0 | 2024-10-15 00:08:08.256 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
cloudless-homeconnect.0 | 2024-10-15 00:08:08.255 | info | terminating
cloudless-homeconnect.0 | 2024-10-15 00:08:08.252 | error | WebSocket is not open: readyState 0 (CONNECTING)
cloudless-homeconnect.0 | 2024-10-15 00:08:08.252 | error | Error:  WebSocket is not open: readyState 0 (CONNECTING)    at WebSocket.send  (C:\Software\ioBroker\node_modules\ws\lib\websocket.js:450:13)    at  Socket.send  (C:\Software\ioBroker\node_modules\iobroker.cloudless-homeconnect\js\Socket.js:149:12)     at Device.send  (C:\Software\ioBroker\node_modules\iobroker.cloudless-homeconnect\js\Device.js:133:12)     at Timeout._onTimeout  (C:\Software\ioBroker\node_modules\iobroker.cloudless-homeconnect\main.js:391:10)     at listOnTimeout (node:internal/timers:581:17)    at  process.processTimers (node:internal/timers:519:7)
cloudless-homeconnect.0 | 2024-10-15 00:08:08.251 | error | uncaught exception: WebSocket is not open: readyState 0 (CONNECTING)
cloudless-homeconnect.0 | 2024-10-15 00:07:51.862 | error | Connection error for device 012090527895006154: AggregateError
cloudless-homeconnect.0 | 2024-10-15 00:07:30.566 | error | Connection error for device 012090527895006154: AggregateError
cloudless-homeconnect.0 | 2024-10-15 00:07:09.211 | info | Adapter started successfully
cloudless-homeconnect.0 | 2024-10-15 00:07:09.191 | info | starting.  Version 1.2.0 (non-npm:  eifel-tech/ioBroker.cloudless-homeconnect#08e461776c4e9c0e634e395508bdc3877d7da0af)  in C:/Software/ioBroker/node_modules/iobroker.cloudless-homeconnect,  node: v20.18.0, js-controller: 7.0.0

**Comment by eifel-tech** [comment]
Neueste Version installieren und nochmal probieren bitte. Wenn das passiert, wenn zum Gerät nicht verbunden werden kann, ließe sich das ja sogar gut reproduzieren oder?

**Comment by Bernd9000** [comment]
Jo
Adapter wird jetzt nicht mehr beendet, AgregatorError bleibt im IOB Log.
Hab dann versucht mit dem Datenpunkt "observe = false" die weiteren Verbindungsversuche zu unterbinden, das klappt nicht.
Der Adapter versucht weiterhin das Gerät zu erreichen.

Log:

cloudless-homeconnect.0 | 2024-10-15 15:50:17.133 | error | Connection error for device 484010534615005556: AggregateError
-- | -- | -- | --
cloudless-homeconnect.0 | 2024-10-15 15:49:55.538 | error | Connection error for device 484010534615005556: AggregateError
cloudless-homeconnect.0 | 2024-10-15 15:49:33.948 | error | Connection error for device 484010534615005556: AggregateError
cloudless-homeconnect.0 | 2024-10-15 15:49:12.374 | error | Connection error for device 484010534615005556: AggregateError
cloudless-homeconnect.0 | 2024-10-15 15:48:50.804 | error | Connection error for device 484010534615005556: AggregateError
cloudless-homeconnect.0 | 2024-10-15 15:48:29.173 | error | Connection error for device 484010534615005556: AggregateError
cloudless-homeconnect.0 | 2024-10-15 15:48:07.593 | error | Connection error for device 484010534615005556: AggregateError
cloudless-homeconnect.0 | 2024-10-15 15:47:46.027 | error | Connection error for device 484010534615005556: AggregateError
cloudless-homeconnect.0 | 2024-10-15 15:47:24.465 | error | Connection error for device 484010534615005556: AggregateError
cloudless-homeconnect.0 | 2024-10-15 15:47:02.924 | error | Connection error for device 484010534615005556: AggregateError
cloudless-homeconnect.0 | 2024-10-15 15:46:41.357 | error | Connection error for device 484010534615005556: AggregateError
cloudless-homeconnect.0 | 2024-10-15 15:46:19.777 | error | Connection error for device 484010534615005556: Error: WebSocket was closed before the connection was established
cloudless-homeconnect.0 | 2024-10-15 15:46:19.776 | info | Gerät mit ID 484010534615005556 wird nicht mehr über den Adapter gesteuert.
cloudless-homeconnect.0 | 2024-10-15 15:46:05.403 | error | Connection error for device 484010534615005556: AggregateError
cloudless-homeconnect.0 | 2024-10-15 15:45:43.832 | info | Gerät mit ID 484010534615005556 kann über den Adapter gesteuert werden.
cloudless-homeconnect.0 | 2024-10-15 15:43:56.173 | info | Adapter started successfully
cloudless-homeconnect.0 | 2024-10-15 15:43:56.152 | info | starting.  Version 1.2.0 (non-npm:  eifel-tech/ioBroker.cloudless-homeconnect#c7703d8b5d7f3bb1bafa916c306a793397fdd9e8)  in C:/Software/ioBroker/node_modules/iobroker.cloudless-homeconnect,  node: v20.18.0, js-controller: 7.0.0

**Comment by Bernd9000** [comment]
Die Nachrichtenrate im IOB sollte bei Info reduziert werden.
Als ich nämlich die Homeconnect App zusätzlich gestartet hatte bei einem nicht erreichbaren Gerät, lief der IOB Log im Milisekundenbereich voll.

**Comment by eifel-tech** [comment]
Ich denke auch, du hast Recht: Die Socketverbindung kann nicht unterbrochen werden, was aber an der Websocket-API selbst liegt. 
- Version 1.2.1: Das Log wird bei Fehlern bei der Socketverbindung nicht mehr zugemüllt. 
- Der AggregateError hat nichts mit dem Adapter selbst zu tun, das liegt an der Socket-API selbst. Diese versucht alle 20 Sekunden etwa, die Verbindung wiederherzustellen und scheitert immer wieder. Darum kommt es jedes Mal wieder zu dem `Connection error for device`. 
- Wegen dem Punkt vorher, klappt auch das "aus der Überwachung nehmen" nicht. Denn dort wird zwar keine neue Connection aufgebaut, die alte probiert es aber immer weiter. Da habe ich leider keinen Einfluss drauf.
- Es wird bei Fehlern jetzt _nicht_ mehr versucht, die Verbindung automatisch wiederherzustellen. Das müsste man durch einen Neustart des Adapters manuell tun, sobald das Gerät wieder erreichbar ist.
