### ISSUE TITLE
Wunsch: Gerätestatus Datenpunkt

### ISSUE THREAD

**Issue by Bernd9000** [eifel-tech/ioBroker.cloudless-homeconnect#124]
Zur besseren Übersicht wäre ein Datenpunkt gut, der Anzeigt ob zum Gerät eine Socket Verbindung besteht.
Also sowas wie online = true oder so.

**Comment by eifel-tech** [comment]
Umgesetzt mit 1.2.3

**Comment by Bernd9000** [comment]
Super, aber geht das nicht pro Gerät ?
Wenn mehrere Geräte vorhanden sind weiß man immer nocht nicht welches Gerät keine Verbindung hat.

**Comment by eifel-tech** [comment]
Ist doch?! `Geräte id -> General -> connected`.

**Comment by Bernd9000** [comment]
Jo, war mein Fehler :-)
War im falschen Zweig.
Danke
