### ISSUE TITLE
Keine Daten bei Siemens Kaffeemaschine EQ9

### ISSUE THREAD

**Issue by Bongo2** [eifel-tech/ioBroker.cloudless-homeconnect#127]
Das Log von Heute:

[debug11.txt](https://github.com/user-attachments/files/17473392/debug11.txt)

Getriggerte Datenpunkte:

[trigger coffeemaker2.txt](https://github.com/user-attachments/files/17473410/trigger.coffeemaker2.txt)

Um 11:01 Uhr habe ich die Instanz neu gestartet.

**Comment by eifel-tech** [comment]
Diese Logs waren sehr gut, da konnte man nämlich sehen, dass es grundsätzlich geht, nämlich bis 01:54:55.305. Bis dahin werden schön jede Minute alle Werte angefragt und von der Maschine auch brav beantwortet. Dann wurde die Verbindung aber vom Gerät geschlossen (`1006: Transport layer broke`) - aus welchen Gründen auch immer. Danach wollte der Adapter die Verbindung wiederherstellen, es passen aber die Verschlüsselungsdaten nicht mehr überein. Daher kommt dann vom Gerät immer `1002: Endpoint received malformed frame`. Um 02:44:05.681 reicht es dem Gerät dann und schaltet sich oder die Schnittstelle vermutlich komplett ab (keine Ahnung, ob die Kaffeemaschine das kann? `Unexpected server response: 404`) und kommt auch nicht wieder hoch, weil der Adapter ja nach 15 Versuchen aufgibt. Da hilft dann nur Neustart. Nach 11:01, als du das dann ja auch getan hast, geht es dann wieder, weil die Verschlüsselungsdaten neu ausgehandelt wurden. So weit meine Theorie :-)
Langer Rede kurzer Sinn, ich habe mal eingebaut, das gleiche zu tun, wie beim Adapterneustart, wenn so etwas wie oben beschrieben auftritt. Probier mal, vielleicht klappt das ja :-)

**Comment by Bongo2** [comment]
Hier sind die Ausgaben von heute:
[debug13.txt](https://github.com/user-attachments/files/17486455/debug13.txt)
[trigger coffeemaker4.txt](https://github.com/user-attachments/files/17486463/trigger.coffeemaker4.txt)

Das ist vermutlich die Zwangstrennung der Fritzbox vom Internet: 
2024-10-23 03:50:33.599  - [32minfo[39m: javascript.0 (220) script.js.common.Trigger_Datenpunkte: cloudless-homeconnect.0.SIEMENS-TI9558X1DE-68A40E7DD334.Status.BackendConnected: false
2024-10-23 03:52:27.740  - [32minfo[39m: javascript.0 (220) script.js.common.Trigger_Datenpunkte: cloudless-homeconnect.0.SIEMENS-TI9558X1DE-68A40E7DD334.Status.BackendConnected: true

Da wurde wegen Backup die Instanz neu gestartet:
2024-10-23 04:15:50.371  - [32minfo[39m: javascript.0 (219) script.js.common.Trigger_Datenpunkte: cloudless-homeconnect.0.info.connection: false
2024-10-23 04:15:51.832  - [32minfo[39m: javascript.0 (219) script.js.common.Trigger_Datenpunkte: cloudless-homeconnect.0.info.connection: true

Im Debug sehe ich das um 2024-10-23 07:19:50.991:
SIEMENS-TI9558X1DE-68A40E7DD334: undefined
Fehler beim Behandeln einer Nachricht von SIEMENS-TI9558X1DE-68A40E7DD334: undefined
Fehlermeldung: SyntaxError: "undefined" is not valid JSON
Closed connection to SIEMENS-TI9558X1DE-68A40E7DD334; reason: 1000
Try to connect to device SIEMENS-TI9558X1DE-68A40E7DD334

Ansonsten sehe ich keine Probleme. Für mich sieht es im Moment gut aus.

Wenn du noch was testen möchtest, mach ich gerne.

**Comment by eifel-tech** [comment]
Das war gestern im debug12-log auch schon drin. Das kommt, weil eine Message an das Gerät gesendet werden soll, obwohl die Connection schon geschlossen wurde. Ist aber nicht schlimm. Ich hab versucht, das in 1.2.4 zu beheben. 
Aber dass es jetzt geht, freut mich, dann mache ich hier mal zu.
