### ISSUE TITLE
Statusmeldungen als Text

### ISSUE THREAD

**Issue by Bongo2** [eifel-tech/ioBroker.cloudless-homeconnect#128]
Ich möchte die ganzen Statusmeldungen wie zum Beispiel bei der Kaffeemaschiene „Wassertank leer“, „Reinigen notwendig“, „Entkalken notwendig“, usw. über meine VIS oder über Sprachassistenten ausgeben. Im Adapter habe ich nur nummerische Werte.
Gibt es irgendwo eine Aufschlüsselung der Werte in Textform? Wäre auch geil, wenn es der Adapter bereitstellen würde.

**Comment by eifel-tech** [comment]
Die Werte im Adapter sind generisch und kommen aus dem Gerät. Die Werte in Textform habe ich nicht und sollte auch nicht in den Adapter, denn dann sind die Datenpunkte ja nicht mehr generisch ;-) Vielleicht wirst du bei der [API-Beschreibung](https://api-docs.home-connect.com/states/?exclude=cleaningRobot%2CcookProcessor%2Ccooktop%2Cdishwasher%2Cdryer%2Cfreezer%2CfridgeFreezer%2Chood%2Coven%2Crefrigerator%2CwarmingDrawer%2Cwasher%2CwasherDryer%2CwineCooler#remote-start-allowance-state) fündig. 
Ansonsten könntest du dir alias-Datenpunkte für die für dich relevanten DPs anlegen und die dann auch sprechend(er) benennen.
