### ISSUE TITLE
Instanz bleibt beim ersten Start gelb

### ISSUE THREAD

**Issue by Bongo2** [eifel-tech/ioBroker.cloudless-homeconnect#129]
Ich habe jetzt die 1.2.4 installiert. Mir ist bei den letzten Malen schon aufgefallen, dass beim ersten Start die Instanz gelb bleibt und `info.connection` false bleibt. Erst nach einem Restart der Instanz wird alles grün.

Hier habe ich schon beim ersten Start auf debug gewechselt:
[debug14.txt](https://github.com/user-attachments/files/17488022/debug14.txt)

**Comment by eifel-tech** [comment]
Sollte in 1.2.5 behoben sein.

**Comment by Bongo2** [comment]
Passt perfekt!

Danke für die Arbeit.

Bis wann ist geplant, dass der Adapter ins ioBroker Repository kommt?

**Comment by eifel-tech** [comment]
Keine Ahnung :-)  da gibt's ja gefühlt tausend Voraussetzungen, die man erfüllen muss, und ich weiß nicht, ob ich die Zeit und Muße habe, mich damit zu beschäftigen...
