### ISSUE TITLE
Unparsable zips received

### ISSUE THREAD

**Issue by Bernd9000** [eifel-tech/ioBroker.cloudless-homeconnect#143]
Wollte seit Gestern mal die neuste Version installieren.
Hab dazu das iob Verzeichniß vorher gelöscht.
Hat sich da was geändert ?

IOB Log:
`<html><body>

cloudless-homeconnect.0 | 2024-11-13 20:59:36.766 | error | Konfiguration unvollständig
-- | -- | -- | --
cloudless-homeconnect.0 | 2024-11-13 20:59:36.766 | error | Konfiguration unvollständig
cloudless-homeconnect.0 | 2024-11-13 20:59:36.766 | error | Unparsable zips received. Please try again later: TypeError: Cannot convert undefined or null to object
cloudless-homeconnect.0 | 2024-11-13 20:59:36.689 | info | Found file: 484010534615005556_DeviceDescription.xml
cloudless-homeconnect.0 | 2024-11-13 20:59:36.689 | info | Found file: 484010534615005556_FeatureMapping.xml
cloudless-homeconnect.0 | 2024-11-13 20:59:36.600 | error | Unparsable zips received. Please try again later: TypeError: Cannot convert undefined or null to object
cloudless-homeconnect.0 | 2024-11-13 20:59:36.498 | info | Found file: 012090527895006154_FeatureMapping.xml
cloudless-homeconnect.0 | 2024-11-13 20:59:36.496 | info | Found file: 012090527895006154_DeviceDescription.xml
cloudless-homeconnect.0 | 2024-11-13 20:59:36.424 | info | Found 2 device(s).
cloudless-homeconnect.0 | 2024-11-13 20:59:36.003 | info | Login sucessfull. Trying to catch token...
cloudless-homeconnect.0 | 2024-11-13 20:59:34.818 | info | starting.  Version 1.2.8 (non-npm:  eifel-tech/ioBroker.cloudless-homeconnect#a07a5fe125289d7fef3a076ea50782ea6a28c87c)  in C:/Software/ioBroker/node_modules/iobroker.cloudless-homeconnect,  node: v20.18.0, js-controller: 7.0.2

</body>
</html>`

**Comment by eifel-tech** [comment]
Grundsätzlich ist es erstmal ne gute Idee, hier das debug log zu posten ;-)
Dann weiß ich nicht, welche Version du vorher hattest. Es wird sich also vielleicht etwas geändert haben, was genau steht [hier](https://github.com/eifel-tech/ioBroker.cloudless-homeconnect?tab=readme-ov-file#changelog) 
Wenn du eine neue Version installierst, musst du grundsätzlich nicht jedes Mal den Datenpunkt `info.config` leeren, es sei denn es steht in den changelogs. Denn dann wird die config ja neu von den Homeconnect-sServern geladen. Dabei kann es auch zu Übertragungsfehlern kommen und das übermittelte ZIP ist dann kaputt. Kann hier so sein, weiß ich aber wie gesagt nicht.

**Comment by Bernd9000** [comment]
Werden die ZIP Dateien irgendwo gespeichert so das ich Sie mir mal anschauen kann ?

**Comment by Bernd9000** [comment]
[Log.txt](https://github.com/user-attachments/files/17739183/Log.txt)

**Comment by Bernd9000** [comment]
Okay, der Fehler tritt bei folgender Funktion auf :

async function xml2json(featuresXml, descriptionXml, typesXml)

Da den Fehler zu finden ist nicht einfach.
Ich mach erstmal dicht,

**Comment by eifel-tech** [comment]
`xml2json` gehört zum Adapter. Wenn du mir `012090527895006154_DeviceDescription.xml` und `012090527895006154_FeatureMapping.xml` sowie `484010534615005556_FeatureMapping.xml` und `484010534615005556_DeviceDescription.xml` schickst, kann ich das debuggen und den Fehler hoffentlich beheben.

**Comment by eifel-tech** [comment]
Kommando zurück. Probier mal bitte die neueste Version des Adapters aus. Ich vermute, das lag an meinen letzten Änderungen für ein anderes Gerät. Das Problem ist, zig Homeconnect-Geräte so unter einen Hut zu bringen, dass es bei allen in allen Konstellationen geht. Und bei dir ist wieder eine neue Variante aufgetaucht *seufz*

**Comment by Bernd9000** [comment]
Ja, funktioniert wieder, Danke

Nur mal angemerkt:
Genau da sehe ich auch das Problem, bei jeder kleinen Änderung von Homeconnect und dann noch eventuell bei jedem einzelnen Gerät wirst Du dein Adapter ändern müssen. Das wird eventuell für Dich eine Vollbeschäftigung hier je mehr Geräte Du unterstützt.

**Comment by eifel-tech** [comment]
Naja, eig hab ich das schon ziemlich generisch gemacht, zumindest hab ich das versucht. Hier hab ich einfach ne Prüfung vergessen, die dann bei dir zum Fehler führte. Der Teufel steckt halt im Detail ;-) 
Freut mich aber, dass es wieder geht. Hab jetzt Version 1.2.9 veröffentlicht, da ist das enthalten.
