### ISSUE TITLE
coffemaker error 

### ISSUE THREAD

**Issue by arteck** [eifel-tech/ioBroker.cloudless-homeconnect#148]
i have here a parse error in row 30
![1732032049792-8b81f7c9-8d6a-4a19-aace-6ae1335dad91-grafik](https://github.com/user-attachments/assets/c3ac05bb-3305-44d8-a3ee-b765700d41a6)

device is a 
![grafik](https://github.com/user-attachments/assets/fd41c82f-428f-4cd4-bbb4-da81b05d4279)

![grafik](https://github.com/user-attachments/assets/5b1e9bc9-507c-4fde-a889-3570a4ae8c25)
![grafik](https://github.com/user-attachments/assets/8804338c-82b2-4c46-8fe5-cd2c7538da83)

enumType 1017 does not exist

my fix is (see code) a try catch block for unknown enums..

**Comment by eifel-tech** [comment]
You are the first case where missing enums occur, so your try-catch is a good solution here :-) Please have a new try. But first you should stop the adapter, clean the content of DP `info.config` and start again. 
If it works, please gibe me some feedback and I'll release a new version. Thanks for your support.

**Comment by arteck** [comment]
yes it works..

**Comment by eifel-tech** [comment]
Fixed in release 1.2.10
