### ISSUE TITLE
rsii definition is wrong / negative

### ISSUE THREAD

**Issue by arteck** [eifel-tech/ioBroker.cloudless-homeconnect#149]
```

cloudless-homeconnect.0 | 2024-11-23 07:38:56.492 | warn | State value to set for "cloudless-homeconnect.0.BOSCH-WTX87M40-68A40E5EB4DB.Status.WiFiSignalStrength" has value "-39" less than min "0"
cloudless-homeconnect.0 | 2024-11-23 07:39:56.492 | warn | State value to set for "cloudless-homeconnect.0.BOSCH-WTX87M40-68A40E5EB4DB.Status.WiFiSignalStrength" has value "-36" less than min "0"
cloudless-homeconnect.0 | 2024-11-23 07:40:56.483 | warn | State value to set for "cloudless-homeconnect.0.BOSCH-WTX87M40-68A40E5EB4DB.Status.WiFiSignalStrength" has value "-40" less than min "0"
cloudless-homeconnect.0 | 2024-11-23 07:41:56.488 | warn | State value to set for "cloudless-homeconnect.0.BOSCH-WTX87M40-68A40E5EB4DB.Status.WiFiSignalStrength" has value "-34" less than min "0"
cloudless-homeconnect.0 | 2024-11-23 07:42:56.491 | warn | State value to set for "cloudless-homeconnect.0.BOSCH-WTX87M40-68A40E5EB4DB.Status.WiFiSignalStrength" has value "-39" less than min "0"
```

**Comment by eifel-tech** [comment]
Would you please send me your `BOSCH-WTX87M40-68A40E5EB4DB_FeatureMapping.xml` and `BOSCH-WTX87M40-68A40E5EB4DB_DeviceDescrption.xml` located in `/opt/iobroker/node_modules/iobroker.cloudless-homeconnect`? The defined min values are from that files.  Perhaps I misunderstood it for that datapoint.

**Comment by arteck** [comment]
WiFiSignalStrength has no min definition

this is coffemaker
```
 "27": {
        "name": "BSH.Common.Status.WiFiSignalStrength",
        "type": "number",
        "access": "read",
        "available": "true",
        "refCID": "12",
        "refDID": "80"
      },
```
this dryer
```

"27": {
        "name": "BSH.Common.Status.WiFiSignalStrength",
        "type": "number",
        "access": "read",
        "available": "true",
        "initValue": "-128",
        "notifyOnChange": "false",
        "refCID": "12",
        "refDID": "84"
      },
```
and this dishwasher
 ```
"27": {
        "name": "BSH.Common.Status.WiFiSignalStrength",
        "type": "number",
        "access": "read",
        "available": "true",
        "initValue": "0",
        "notifyOnChange": "false",
        "refCID": "12",
        "refDID": "84"
      },
```

**Comment by eifel-tech** [comment]
But perhaps in combination of both files... I want to understand how the values come about. So would you please send me both files?

**Comment by arteck** [comment]
[dryer.zip](https://github.com/user-attachments/files/17920811/dryer.zip)

**Comment by eifel-tech** [comment]
Thank you. Please try again. After removing the DP and restarting the adapter the warning shouldn't occur anymore.

**Comment by arteck** [comment]
works but
`Connection interrupted for device BOSCH-WTX87M40-68A40E5EB4DB: Error: getaddrinfo ENOTFOUND bosch-wtx87m40-68a40e5eb4db`

the dryer is now offline..

**Comment by eifel-tech** [comment]
I moved the log to debug. 
For some devices (like your dryer) it's normal to be offline if you power off the device but for others not, for them a warning would be more correct. Unfortunately I don't know a parameter to detect that devices. 
The `number of connection attempts` only configures how often the message would occur, nothing more.
