### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by SaimenSays** [eifel-tech/ioBroker.cloudless-homeconnect#67]
Hallo,
vielen Dank für die Mühen in Richtung einer Verbindungsmöglichkeit ohne Cloudanbindung!
Wird es demnächst ein Release dieses Adapters geben, welcher über iobroker installierbar ist? Auch über npm direkt scheint es aktuell nicht zu funktioneren?

**Comment by eifel-tech** [comment]
Hallo,
für ein Release ist es m.E. zu früh. Der Adapter funktioniert mit einem Gerät definitiv, für die Weiterentwicklung/Test bzw. gar ein Release fehlen mir aber ein paar weitere Geräte ;-)
Aber installieren kannst du den Adapter doch trotzdem: Im iobroker Adapter Tab und dann wie auf dem Bild vorgehen.
![image](https://github.com/eifel-tech/ioBroker.cloudless-homeconnect/assets/59030120/e686f8f3-05dd-4b03-b211-e3031e36aa5c)
