### ISSUE TITLE
Unhandled promise rejection

### ISSUE THREAD

**Issue by SaimenSays** [eifel-tech/ioBroker.cloudless-homeconnect#68]
Der Adapter ist direkt aus github installiert. 
Die Verbindung scheint zu stande zu kommen. Es ist ein Gerät registriert, welches auch gefunden wird. Dann scheint es aber ein Problem zu geben. Kann man mit dem Log etwas anfangen?

```
2024-07-03 17:15:55.949  - info: host.Automation instance system.adapter.cloudless-homeconnect.0 started with pid 2425085
2024-07-03 17:15:57.053  - info:  cloudless-homeconnect.0 (2425085) starting. Version 1.0.3 (non-npm:  eifel-tech/ioBroker.cloudless-homeconnect#4dd20a3fc5f888d1b231cdf631f43983c9e59b9d)  in /opt/iobroker/node_modules/iobroker.cloudless-homeconnect, node:  v20.13.1, js-controller: 5.0.19
2024-07-03 17:15:58.339  - info: cloudless-homeconnect.0 (2425085) Login sucessfull. Trying to catch token...
2024-07-03 17:15:58.910  - info: cloudless-homeconnect.0 (2425085) Found 1 device(s).
2024-07-03 17:15:59.412  - error:  cloudless-homeconnect.0 (2425085) Unhandled promise rejection. This  error originated either by throwing inside of an async function without a  catch block, or by rejecting a promise which was not handled with  .catch().
2024-07-03 17:15:59.413  - error: cloudless-homeconnect.0 (2425085) unhandled promise rejection: Cannot convert undefined or null to object
2024-07-03 17:15:59.414  - error: cloudless-homeconnect.0 (2425085) TypeError: Cannot convert undefined or null to object
at Function.values ()
at Object.xml2json (/opt/iobroker/node_modules/iobroker.cloudless-homeconnect/js/Xml2JsonConverter.js:159:9)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async CloudlessHomeconnect.loadConfig (/opt/iobroker/node_modules/iobroker.cloudless-homeconnect/main.js:362:23)
at async CloudlessHomeconnect.onReady (/opt/iobroker/node_modules/iobroker.cloudless-homeconnect/main.js:87:25)
2024-07-03 17:15:59.414  - error: cloudless-homeconnect.0 (2425085) Cannot convert undefined or null to object
2024-07-03 17:15:59.419  - info: cloudless-homeconnect.0 (2425085) terminating
2024-07-03 17:15:59.419  - warn: cloudless-homeconnect.0 (2425085) Terminated (UNCAUGHT_EXCEPTION): Without reason
2024-07-03 17:15:59.920  - info: cloudless-homeconnect.0 (2425085) terminating
2024-07-03 17:16:00.018  - error: host.Automation instance system.adapter.cloudless-homeconnect.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
```

**Comment by eifel-tech** [comment]
- Was für ein Gerät ist das denn? Ist dieses über die offizielle Homeconnect App steuerbar? 
- Steht im Datenpunkt `info.config` etwas drin? 
- Wäre es möglich, den Adapter mit Logstufe `debug` zu starten und dieses zur Verfügung zu stellen? Vielleicht kann ich dann etwas mehr sehen. Danke

**Comment by SaimenSays** [comment]
- Es ist ein Geschirrspüler SN63EX02CE. Der Geschirrspüler lässt sich über die App starten. (Dies wäre auch genau mein Anwendungsfall, sobald gegen mittag ausreichend PV-Leistung vorhanden ist)
- Der Datenpunkt info.config ist vorhanden, aber kein Wert abgelegt.
- Ich habe den Adapter mit Loglevel debug gestaret. Es werden aber Access Tokens und möglicherweise andere Sicherheitsrelevante Information ausgegeben, von daher möchte ich es nicht komplett öffentlich posten. Was mir aber direkt aufgefallen ist - obwohl zuerst "Login successfull" geloggt wird, kommt ein paar Anfragen später scheinbar eine Loginseite als Antwort. Habe das Passwort auf singlekey-id.com getestet und im Adapter neu gesetzt, scheint korrekt zu sein.

![grafik](https://github.com/eifel-tech/ioBroker.cloudless-homeconnect/assets/10372066/db9b9500-1db5-4dd6-8c8c-90ac064c1873)

**Comment by eifel-tech** [comment]
Also das Gerät wird wohl gefunden und der Login beim Hersteller klappt auch. Der Adapter kann aber das zurückgelieferte XML nicht parsen - ist auch plausibel, denn bei mir läuft der Adapter mit einem Backofen. Ein Geschirrspüler hat sicherlich andere Features ;-)
Ich habe nun noch eine Logausgabe eingebaut, wo im Debug-Modus die XMLs ausgegeben werden. Diese hätte ich gerne, dann kann ich lokal ein wenig rumprobieren. Dafür müsstest du den Adapter bitte nochmal neu installieren. Kannst du mir die schicken? Aber bitte als Text, nicht als Bild... Danke vorab.

**Comment by SaimenSays** [comment]
Danke für die Mühe, sich der Sache anzunehmen!
Hoffe das hilft weiter...

`<?xml version="1.0" encoding="UTF-8"?><device xmlns="http://www.home-connect.com/schemas/DeviceDescription/20140417" xmlns:xi="http://www.w3.org/2001/XInclude" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" treatment="lazy" xsi:schemaLocation="http://www.home-connect.com/schemas/DeviceDescription/20140417 https://www.home-connect.com/schemas/DeviceDescription/20140417/HC_INT_BSH_DeviceDescription.xsd"><!-- BSH "Remote Operation" content type declarations ("cidList") --><xi:include href="https://www.home-connect.com/schemas/DeviceDescription/20140417/HC_INT_BSH_CTD.xml" parse="xml"><xi:fallback><error>xinclude error: file "HC_INT_BSH_CTD.xml" not found</error></xi:fallback></xi:include><!-- BSH "Remote Operation" data type declarations ("didList") --><xi:include href="https://www.home-connect.com/schemas/DeviceDescription/20140417/HC_INT_BSH_DTD.xml" parse="xml"><xi:fallback><error>xinclude error: file "HC_INT_BSH_DTD.xml" not found</error></xi:fallback></xi:include><!-- BSH "Remote Operation" device/appliance type declarations ("devList") --><xi:include href="https://www.home-connect.com/schemas/DeviceDescription/20140417/HC_INT_BSH_DEV.xml" parse="xml"><xi:fallback><error>xinclude error: file "HC_INT_BSH_DEV.xml" not found</error></xi:fallback></xi:include><description><!-- Yellowbox scope=Dishcare.8.4.0 overload= --><!-- Redbox identifier= --><!-- Appliance name --><type>Dishwasher</type><!-- Brand name --><brand>SIEMENS</brand><!-- VIB --><model>SN63EX02CE</model><!-- DDF version --><version>5</version><!-- DDF revision --><revision>2</revision><!-- Pair-able end-devices --><pairableDeviceTypes><deviceType>Application</deviceType></pairableDeviceTypes></description><!--BSH.Common.Root.StatusList --><statusList access="read" available="true" uid="0102"><!--BSH.Common.Status.BackendConnected --><status access="read" available="true" refCID="01" refDID="00" uid="0005"/><!--BSH.Common.Status.RemoteControlStartAllowed --><status access="read" available="true" refCID="01" refDID="00" uid="0205"/><!--BSH.Common.Status.RemoteControlActive --><status access="read" available="true" refCID="01" refDID="00" uid="020B"/><!--BSH.Common.Status.DoorState --><status access="read" available="true" enumerationType="0201" refCID="03" refDID="80" uid="020F"/><!--BSH.Common.Status.OperationState --><status access="read" available="true" enumerationType="0203" refCID="03" refDID="80" uid="0228"/><!--BSH.Common.Status.SoftwareUpdateTransactionID --><status access="read" available="true" refCID="26" refDID="83" uid="0250"/><!--BSH.Common.Status.ErrorCodesList --><status access="read" available="true" refCID="85" refDID="408B" uid="0266"/><!--BSH.Common.Status.Program.All.Count.Started --><status access="read" available="false" refCID="02" refDID="81" uid="0267"/><!--BSH.Common.Status.ProgramSessionSummary.Latest --><status access="read" available="true" refCID="3F" refDID="8D" uid="0271"/><!--BSH.Common.Status.ProgramRunDetail.EndTrigger --><status access="read" available="true" enumerationType="0235" refCID="03" refDID="80" uid="0272"/><!--Dishcare.Dishwasher.Status.ProgramPhase --><status access="read" available="true" enumerationType="1005" refCID="03" refDID="80" uid="1000"/><!--Dishcare.Dishwasher.Status.SilenceOnDemandRemainingTime --><status access="read" available="true" refCID="10" refDID="82" uid="1005"/><!--Dishcare.Dishwasher.Status.EcoDryActive --><status access="read" available="true" refCID="01" refDID="00" uid="1007"/><!--BSH.Common.Status.Favorite.Handling --><status access="read" available="true" enumerationType="0227" refCID="03" refDID="80" uid="8003"/></statusList><!--BSH.Common.Root.SettingList --><settingList access="readWrite" available="true" uid="0103"><!--BSH.Common.Setting.AllowBackendConnection --><setting access="readWrite" available="true" refCID="01" refDID="00" uid="0003"/><!--BSH.Common.Setting.PowerState --><setting access="readWrite" available="true" enumerationType="0204" refCID="03" refDID="80" uid="021B"/><!--BSH.Common.Setting.RemoteControlLevel --><setting access="readWrite" available="true" enumerationType="0221" refCID="03" refDID="80" uid="000F"/><!--Dishcare.Dishwasher.Setting.RinseAid --><setting access="readWrite" available="true" enumerationType="1000" refCID="03" refDID="80" uid="1102"/><!--Dishcare.Dishwasher.Setting.ExtraDry --><setting access="readWrite" available="true" refCID="01" refDID="00" uid="1104"/><!--Dishcare.Dishwasher.Setting.SilenceOnDemandDefaultTime --><setting access="readWrite" available="true" max="1800" min="60" refCID="10" refDID="82" stepSize="60" uid="111E"/><!--Dishcare.Dishwasher.Setting.SensitivityTurbidity --><setting access="readWrite" available="true" enumerationType="1004" refCID="03" refDID="80" uid="1103"/><!--Dishcare.Dishwasher.Setting.HotWater --><setting access="readWrite" available="true" enumerationType="100A" refCID="03" refDID="80" uid="1105"/><!--Dishcare.Dishwasher.Setting.EcoAsDefault --><setting access="readWrite" available="true" enumerationType="100B" refCID="03" refDID="80" uid="110B"/><!--Dishcare.Dishwasher.Setting.SoundLevelSignal --><setting access="readWrite" available="true" enumerationType="1001" refCID="03" refDID="80" uid="110C"/><!--Dishcare.Dishwasher.Setting.WaterHardness --><setting access="readWrite" available="true" enumerationType="1009" refCID="03" refDID="80" uid="110F"/><!--Dishcare.Dishwasher.Setting.InfoLight --><setting access="readWrite" available="true" refCID="01" refDID="00" uid="111A"/><!--Dishcare.Dishwasher.Setting.DryingAssistantAllPrograms --><setting access="readWrite" available="true" enumerationType="100F" refCID="03" refDID="80" uid="111D"/><!--Dishcare.Dishwasher.Setting.SpeedOnDemand --><setting access="read" available="true" refCID="01" refDID="00" uid="1120"/><!--BSH.Common.Setting.Favorite.001.Functionality --><setting access="readWrite" available="true" enumerationType="0225" refCID="03" refDID="80" uid="8038"/><!--BSH.Common.Setting.Favorite.001.Name --><setting access="readWrite" available="true" max="30" min="0" refCID="05" refDID="8B" uid="8039"/><!--BSH.Common.Setting.Favorite.001.Program --><setting access="readWrite" available="true" max="1" min="0" refCID="A8" refDID="408D" uid="803A"/></settingList><!--BSH.Common.Root.EventList --><eventList uid="0104"><!--BSH.Common.Event.SoftwareUpdateAvailable --><event enumerationType="0001" handling="acknowledge" level="hint" refCID="03" refDID="80" uid="0015"/><!--BSH.Common.Event.ConfirmPermanentRemoteStart --><event enumerationType="0001" handling="none" level="hint" refCID="03" refDID="80" uid="002E"/><!--BSH.Common.Event.AquaStopOccured --><event enumerationType="0001" handling="none" level="critical" refCID="03" refDID="80" uid="020D"/><!--BSH.Common.Event.ProgramFinished --><event enumerationType="0001" handling="none" level="hint" refCID="03" refDID="80" uid="021C"/><!--BSH.Common.Event.LowWaterPressure --><event enumerationType="0001" handling="none" level="alert" refCID="03" refDID="80" uid="021F"/><!--BSH.Common.Event.ProgramAborted --><event enumerationType="0001" handling="acknowledge" level="hint" refCID="03" refDID="80" uid="0221"/><!--BSH.Common.Event.ConnectLocalWiFi --><event enumerationType="0001" handling="none" level="warning" refCID="03" refDID="80" uid="0241"/><!--BSH.Common.Event.SoftwareDownloadAvailable --><event enumerationType="0001" handling="acknowledge" level="hint" refCID="03" refDID="80" uid="0251"/><!--BSH.Common.Event.SoftwareUpdateSuccessful --><event enumerationType="0001" handling="acknowledge" level="hint" refCID="03" refDID="80" uid="0253"/><!--Dishcare.Dishwasher.Event.InternalError --><event enumerationType="0001" handling="none" level="alert" refCID="03" refDID="80" uid="1200"/><!--Dishcare.Dishwasher.Event.CheckFilterSystem --><event enumerationType="0001" handling="none" level="alert" refCID="03" refDID="80" uid="1201"/><!--Dishcare.Dishwasher.Event.DrainingNotPossible --><event enumerationType="0001" handling="none" level="alert" refCID="03" refDID="80" uid="1202"/><!--Dishcare.Dishwasher.Event.DrainPumpBlocked --><event enumerationType="0001" handling="none" level="alert" refCID="03" refDID="80" uid="1203"/><!--Dishcare.Dishwasher.Event.WaterheaterCalcified --><event enumerationType="0001" handling="none" level="alert" refCID="03" refDID="80" uid="1204"/><!--Dishcare.Dishwasher.Event.LowVoltage --><event enumerationType="0001" handling="none" level="alert" refCID="03" refDID="80" uid="1205"/><!--Dishcare.Dishwasher.Event.RinseAidLack --><event enumerationType="0001" handling="none" level="hint" refCID="03" refDID="80" uid="1211"/><!--Dishcare.Dishwasher.Event.RinseAidNearlyEmpty --><event enumerationType="0001" handling="none" level="hint" refCID="03" refDID="80" uid="1213"/><!--Dishcare.Dishwasher.Event.SmartFilterCleaningReminder --><event enumerationType="0001" handling="acknowledge" level="hint" refCID="03" refDID="80" uid="1234"/><!--Dishcare.Dishwasher.Event.SaltLack --><event enumerationType="0001" handling="none" level="hint" refCID="03" refDID="80" uid="1210"/><!--Dishcare.Dishwasher.Event.SaltNearlyEmpty --><event enumerationType="0001" handling="none" level="hint" refCID="03" refDID="80" uid="1212"/><!--Dishcare.Dishwasher.Event.MachineCareReminder --><event enumerationType="0001" handling="acknowledge" level="hint" refCID="03" refDID="80" uid="1214"/><!--Dishcare.Dishwasher.Event.MachineCareAndFilterCleaningReminder --><event enumerationType="0001" handling="acknowledge" level="hint" refCID="03" refDID="80" uid="122F"/></eventList><!--BSH.Common.Root.CommandList --><commandList access="writeOnly" available="true" uid="0105"><!--BSH.Common.Command.DeactivateWiFi --><command access="writeOnly" available="true" refCID="01" refDID="00" uid="0001"/><!--BSH.Common.Command.AcknowledgeEvent --><command access="writeOnly" available="true" refCID="15" refDID="81" uid="0006"/><!--BSH.Common.Command.RejectEvent --><command access="writeOnly" available="true" refCID="15" refDID="81" uid="0010"/><!--BSH.Common.Command.AbortProgram --><command access="none" available="true" refCID="01" refDID="00" uid="0200"/><!--BSH.Common.Command.ApplyFactoryReset --><command access="writeOnly" available="true" refCID="01" refDID="00" uid="0229"/><!--BSH.Common.Command.DeactivateRemoteControlStart --><command access="writeOnly" available="true" refCID="01" refDID="00" uid="022B"/><!--BSH.Common.Command.AllowSoftwareUpdate --><command access="writeOnly" available="true" refCID="01" refDID="00" uid="0263"/><!--BSH.Common.Command.AllowSoftwareDownload --><command access="writeOnly" available="true" refCID="01" refDID="00" uid="0252"/><!--BSH.Common.Command.SetWaterHardness --><command access="writeOnly" available="true" refCID="18" refDID="81" uid="022C"/></commandList><!--BSH.Common.Root.OptionList --><optionList access="readWrite" available="true" uid="0106"><!--BSH.Common.Option.ProgramProgress --><option access="read" available="true" refCID="11" refDID="A0" uid="021E"/><!--BSH.Common.Option.RemainingProgramTime --><option access="read" available="true" refCID="10" refDID="82" uid="0220"/><!--BSH.Common.Option.RemainingProgramTimeIsEstimated --><option access="read" available="true" initValue="1" refCID="01" refDID="00" uid="0225"/><!--BSH.Common.Option.StartInRelative --><option access="read" available="true" max="86400" min="0" refCID="10" refDID="82" uid="022E"/><!--BSH.Common.Option.EnergyForecast --><option access="read" available="true" refCID="11" refDID="A0" uid="0231"/><!--BSH.Common.Option.WaterForecast --><option access="read" available="true" refCID="11" refDID="A0" uid="0232"/><!--Dishcare.Dishwasher.Option.SilenceOnDemand --><option access="readWrite" available="true" default="false" refCID="01" refDID="00" uid="1410"/><!--Dishcare.Dishwasher.Option.HygienePlus --><option access="readWrite" available="true" default="false" refCID="01" refDID="00" uid="1403"/><!--Dishcare.Dishwasher.Option.HalfLoad --><option access="readWrite" available="true" default="false" refCID="01" refDID="00" uid="1404"/><!--Dishcare.Dishwasher.Option.IntensivZone --><option access="readWrite" available="true" default="false" refCID="01" refDID="00" uid="1406"/><!--Dishcare.Dishwasher.Option.VarioSpeedPlus --><option access="readWrite" available="true" default="false" refCID="01" refDID="00" uid="1407"/><!--BSH.Common.Option.ProgramName --><option access="read" available="true" refCID="05" refDID="8B" uid="8004"/><!--BSH.Common.Option.BaseProgram --><option access="readWrite" available="true" refCID="15" refDID="81" uid="8005"/></optionList><!--BSH.Common.Root.ProgramGroup --><programGroup available="true" uid="0107"><!--Dishcare.Dishwasher.Program.Intensiv70 --><program available="true" uid="2000"><!--BSH.Common.Option.StartInRelative --><option access="readWrite" available="true" liveUpdate="false" refUID="022E"/><!--Dishcare.Dishwasher.Option.HygienePlus --><option access="readWrite" available="true" liveUpdate="true" refUID="1403"/><!--Dishcare.Dishwasher.Option.HalfLoad --><option access="readWrite" available="true" liveUpdate="true" refUID="1404"/><!--Dishcare.Dishwasher.Option.IntensivZone --><option access="readWrite" available="true" liveUpdate="true" refUID="1406"/><!--Dishcare.Dishwasher.Option.VarioSpeedPlus --><option access="readWrite" available="true" liveUpdate="true" refUID="1407"/><!--Dishcare.Dishwasher.Option.SilenceOnDemand --><option access="readWrite" available="true" liveUpdate="true" refUID="1410"/></program><!--Dishcare.Dishwasher.Program.Auto2 --><program available="true" uid="2003"><!--BSH.Common.Option.StartInRelative --><option access="readWrite" available="true" liveUpdate="false" refUID="022E"/><!--Dishcare.Dishwasher.Option.HygienePlus --><option access="readWrite" available="true" liveUpdate="true" refUID="1403"/><!--Dishcare.Dishwasher.Option.HalfLoad --><option access="readWrite" available="true" liveUpdate="true" refUID="1404"/><!--Dishcare.Dishwasher.Option.IntensivZone --><option access="readWrite" available="true" liveUpdate="true" refUID="1406"/><!--Dishcare.Dishwasher.Option.VarioSpeedPlus --><option access="readWrite" available="true" liveUpdate="true" refUID="1407"/><!--Dishcare.Dishwasher.Option.SilenceOnDemand --><option access="readWrite" available="true" liveUpdate="true" refUID="1410"/></program><!--Dishcare.Dishwasher.Program.Eco50 --><program available="true" uid="2004"><!--BSH.Common.Option.StartInRelative --><option access="readWrite" available="true" liveUpdate="false" refUID="022E"/><!--Dishcare.Dishwasher.Option.HygienePlus --><option access="readWrite" available="true" liveUpdate="true" refUID="1403"/><!--Dishcare.Dishwasher.Option.HalfLoad --><option access="readWrite" available="true" liveUpdate="true" refUID="1404"/><!--Dishcare.Dishwasher.Option.IntensivZone --><option access="readWrite" available="true" liveUpdate="true" refUID="1406"/><!--Dishcare.Dishwasher.Option.VarioSpeedPlus --><option access="readWrite" available="true" liveUpdate="true" refUID="1407"/><!--Dishcare.Dishwasher.Option.SilenceOnDemand --><option access="readWrite" available="true" liveUpdate="true" refUID="1410"/></program><!--Dishcare.Dishwasher.Program.Quick45 --><program available="true" uid="2007"><!--BSH.Common.Option.StartInRelative --><option access="readWrite" available="true" liveUpdate="false" refUID="022E"/><!--Dishcare.Dishwasher.Option.SilenceOnDemand --><option access="readWrite" available="true" liveUpdate="true" refUID="1410"/></program><!--Dishcare.Dishwasher.Program.PreRinse --><program available="true" uid="2008"><!--BSH.Common.Option.StartInRelative --><option access="readWrite" available="true" liveUpdate="false" refUID="022E"/><!--Dishcare.Dishwasher.Option.SilenceOnDemand --><option access="readWrite" available="true" liveUpdate="true" refUID="1410"/></program><!--Dishcare.Dishwasher.Program.Quick65 --><program available="true" uid="200B"><!--BSH.Common.Option.StartInRelative --><option access="readWrite" available="true" liveUpdate="false" refUID="022E"/><!--Dishcare.Dishwasher.Option.SilenceOnDemand --><option access="readWrite" available="true" liveUpdate="true" refUID="1410"/></program><!--Dishcare.Dishwasher.Program.MachineCare --><program available="true" uid="2017"><!--BSH.Common.Option.StartInRelative --><option access="readWrite" available="true" liveUpdate="false" refUID="022E"/><!--Dishcare.Dishwasher.Option.SilenceOnDemand --><option access="readWrite" available="true" liveUpdate="true" refUID="1410"/></program><!--BSH.Common.Program.Favorite.001 --><program available="true" uid="803C"><!--BSH.Common.Option.ProgramName --><option access="read" available="true" default="&#34;&#34;" liveUpdate="true" refUID="8004"/><!--BSH.Common.Option.BaseProgram --><option access="readWrite" available="true" default="0" liveUpdate="true" refUID="8005"/><!--BSH.Common.Option.StartInRelative --><option access="readWrite" available="true" liveUpdate="false" refUID="022E"/><!--Dishcare.Dishwasher.Option.HygienePlus --><option access="readWrite" available="true" liveUpdate="true" refUID="1403"/><!--Dishcare.Dishwasher.Option.HalfLoad --><option access="readWrite" available="true" liveUpdate="true" refUID="1404"/><!--Dishcare.Dishwasher.Option.IntensivZone --><option access="readWrite" available="true" liveUpdate="true" refUID="1406"/><!--Dishcare.Dishwasher.Option.VarioSpeedPlus --><option access="readWrite" available="true" liveUpdate="true" refUID="1407"/><!--Dishcare.Dishwasher.Option.SilenceOnDemand --><option access="readWrite" available="true" liveUpdate="true" refUID="1410"/></program></programGroup><!--BSH.Common.Root.ActiveProgram --><activeProgram access="readWrite" uid="0100"/><!--BSH.Common.Root.SelectedProgram --><selectedProgram access="readWrite" fullOptionSet="false" uid="0101"/><enumerationTypeList><!--Dishcare.Dishwasher.EnumType.ProgramPhase --><enumerationType enid="1005"><!--None --><enumeration value="0"/><!--PreRinse --><enumeration value="1"/><!--MainWash --><enumeration value="2"/><!--FinalRinse --><enumeration value="3"/><!--Drying --><enumeration value="4"/></enumerationType><!--Dishcare.Dishwasher.EnumType.WaterHardness --><enumerationType enid="1009"><!--H00 --><enumeration value="0"/><!--H01 --><enumeration value="1"/><!--H02 --><enumeration value="2"/><!--H03 --><enumeration value="3"/><!--H04 --><enumeration value="4"/><!--H05 --><enumeration value="5"/><!--H06 --><enumeration value="6"/><!--H07 --><enumeration value="7"/></enumerationType><!--Dishcare.Dishwasher.EnumType.SignalSoundLevel --><enumerationType enid="1001"><!--Off --><enumeration value="0"/><!--Low --><enumeration value="1"/><!--Medium --><enumeration value="2"/><!--High --><enumeration value="3"/></enumerationType><!--BSH.Common.EnumType.ProgramRunDetail.EndTrigger --><enumerationType enid="0235"><!--ProgramFinished --><enumeration value="0"/><!--ProgramAbortedByUser --><enumeration value="1"/><!--ProgramAbortedByAppliance --><enumeration value="2"/><!--ProgramAbortedByApplianceCriticalError --><enumeration value="3"/></enumerationType><!--BSH.Common.EnumType.EventPresentState --><enumerationType enid="0001"><!--Off --><enumeration value="0"/><!--Present --><enumeration value="1"/><!--Confirmed --><enumeration value="2"/></enumerationType><!--Dishcare.Dishwasher.EnumType.SensitivityTurbidityAdjustement --><enumerationType enid="1004"><!--Standard --><enumeration value="0"/><!--Sensitive --><enumeration value="1"/><!--VerySensitive --><enumeration value="2"/></enumerationType><!--BSH.Common.EnumType.Favorite.Handling --><enumerationType enid="0227"><!--AsList --><enumeration value="0"/><!--AsButtons --><enumeration value="1"/></enumerationType><!--BSH.Common.EnumType.OperationState --><enumerationType enid="0203"><!--Inactive --><enumeration value="0"/><!--Ready --><enumeration value="1"/><!--DelayedStart --><enumeration value="2"/><!--Run --><enumeration value="3"/><!--Pause --><enumeration value="4"/><!--ActionRequired --><enumeration value="5"/><!--Finished --><enumeration value="6"/><!--Error --><enumeration value="7"/><!--Aborting --><enumeration value="8"/></enumerationType><!--BSH.Common.EnumType.DoorState --><enumerationType enid="0201"><!--Open --><enumeration value="0"/><!--Closed --><enumeration value="1"/></enumerationType><!--BSH.Common.EnumType.RemoteControlLevel --><enumerationType enid="0221"><!--Monitoring --><enumeration value="0"/><!--ManualRemoteStart --><enumeration value="1"/><!--PermanentRemoteStart --><enumeration value="2"/></enumerationType><!--Dishcare.Dishwasher.EnumType.RinseAid --><enumerationType enid="1000"><!--Off --><enumeration value="0"/><!--R01 --><enumeration value="1"/><!--R02 --><enumeration value="2"/><!--R03 --><enumeration value="3"/><!--R04 --><enumeration value="4"/><!--R05 --><enumeration value="5"/><!--R06 --><enumeration value="6"/></enumerationType><!--Dishcare.Dishwasher.EnumType.EcoAsDefault --><enumerationType enid="100B"><!--LastProgram --><enumeration value="0"/><!--EcoAsDefault --><enumeration value="1"/></enumerationType><!--BSH.Common.EnumType.PowerState --><enumerationType enid="0204"><!--Off --><enumeration value="1"/><!--On --><enumeration value="2"/></enumerationType><!--BSH.Common.EnumType.Favorite.Functionality --><enumerationType enid="0225"><!--Off --><enumeration value="0"/><!--Program --><enumeration value="1"/></enumerationType><!--Dishcare.Dishwasher.EnumType.HotWater --><enumerationType enid="100A"><!--ColdWater --><enumeration value="0"/><!--HotWater --><enumeration value="1"/></enumerationType><!--Dishcare.Dishwasher.EnumType.DryingAssistantAllPrograms --><enumerationType enid="100F"><!--Off --><enumeration value="0"/><!--AllPrograms --><enumeration value="1"/><!--EcoAsDefault --><enumeration value="2"/></enumerationType></enumerationTypeList></device>`

**Comment by eifel-tech** [comment]
Danke. Wird da auch noch das Feature-XML ausgegeben?

**Comment by SaimenSays** [comment]
Irgendwie bekomme ich das nicht ordentlich angezeigt/extrahiert. Der log viewer von iobroker kommt wohl mit dem xml nicht klar, und stellt die Feature xml gar nicht dar. Im Download ist das dann eine geparste Tabelle, also auch nicht brauchbar. Wäre es eventuell sinnvoller die xml als Datei abzulegen, dann könnte ich die einfach hochladen. Oder wird das eventuell schon gemacht, auch wenn ich es auf anhieb nicht finden konnte?

**Comment by eifel-tech** [comment]
Kannst du nochmal neu installieren bitte? Ich hab im Parser ein bisschen was geändert. Vielleicht geht es ja jetzt.

**Comment by SaimenSays** [comment]
> Nee als Datei ablegen geht nicht. Das würde ja dann immer gemacht und im Normalbetrieb ist das ja nicht nötig. Das müllt das Dateisystem zu, ganz abgesehen davon, dass der Adapter ja evtl. gar keine Zugriffsberechtigung hat _schulterzuck_ Vielleicht die Logs über die Konsole angucken? Da dürfte es dann doch eig auch nicht formatiert werden oder? Leider braucht man die XML auch zwingend, sonst werden die Features, auf die im Device-XML verlinkt wird, ja nicht gefunden :-(

Bin zwar kein iobroker Entwickler, denke es sollte für den Adapter kein Problem sein, Dateien in das Verzeichnis `iobroker-data/cloudless-homeconnect.0` abzulegen. Das machen andere Adapter auch so. Node-red legt z.B. dort die flows.json oder auch der esphome adapter legt dort die yaml Konfigurationen der ESPs ab. Auch sollte es nichts vermüllen. Die Dateien sind immer nach dem Schema "Seriennummer_FeatureMapping.xml" benannt. Es würde also maximal die Datei überschreiben. Aber das könnte man wohl auch noch so hinbiegen, dass die Dateien nur geschrieben werden, wenn der Adaper auf log level Debug steht.

**Comment by SaimenSays** [comment]
> Kannst du nochmal neu installieren bitte? Ich hab im Parser ein bisschen was geändert. Vielleicht geht es ja jetzt.

Es geht voran :-)
Der Adapter bleibt aktiv, und es wird der Geschirrspüler angezeigt, aber die Objekte füllen sich nicht. 
Welche Ports müssen offen sein? Eventuell ein Problem mit meiner Firewall?
![grafik](https://github.com/eifel-tech/ioBroker.cloudless-homeconnect/assets/10372066/6f3f75b0-bb02-43a2-86a9-b270736e2ecb)

Und hier noch der letzte Teil des log mit Fehler:
![grafik](https://github.com/eifel-tech/ioBroker.cloudless-homeconnect/assets/10372066/271e5bd0-29da-416d-9596-61f1947d2a49)

In `info.config` ist eine leeres Array drin. Der Fehler besagt, dass ich die Adapterkonfiguration anpassen soll, aber dort ist nur Email und Passwort, und das ist ja korrekt - verstehe die Fehlermeldung nicht. 
Woher kennt der Adapter die lokale IP des Geschirrspülers? Ist die etwa in der Cloud abgelegt?

**Comment by SaimenSays** [comment]
> Danke. Wird da auch noch das Feature-XML ausgegeben?

Ich habe nochmal den allten Commit "Zusätzliche Logausgaben" installiert. Es sieht so aus, als würde das _Feature.xml gar nicht geloggt. Es fehlt ein Eintrag, wie der des Device. Hier die Ausgabe im Browser, wenn ich das Logfile aus iobroker downloade, eingekürtzt, sodass es einigermaßen überschaubar ist:
![grafik](https://github.com/eifel-tech/ioBroker.cloudless-homeconnect/assets/10372066/62123692-85d3-489d-8e6e-5f9134d5f14b)

**Comment by eifel-tech** [comment]
Also ich bin davon ausgegangen, dass er ein Feature XML bekommt. Aber wenn info.config leer ist, scheint das wirklich nicht so zu sein. 
Ich habe nochmal ein paar Logausgaben hinzugefügt. Der Adapter geht halt davon aus, dass wenn er durch die config Methode durchgelaufen ist, etwas in info.config drin steht. Deswegen die "kuriose" Fehlermeldung. Wenn du testest, müsstest du bitte den Datenpunkt editieren und den Inhalt löschen. Danach sollte er wieder versuchen, die config zu holen. 
Sorry für das hin und her, aber ich habe im Moment keine Idee, warum das Feature nicht kommt :-( ich hoffe es macht dir nichts aus, als Testobjekt zu fungieren ;-)

**Comment by SaimenSays** [comment]
Schön wenn sich jemand die Arbeit macht eine Anbindung zu programmieren! Da ist mal etwas Testen das geringste Problem. 

Keine Ahnung warum, in dem letzten Commit ist nur das Logging geändert. Aber es funktioniert nach kleineren Hürden nun auf wundersame Weise.
Zwei Hürden musste ich noch nehmen:

- Fehler `Connection error for device 014060394189002726: Error: getaddrinfo ENOTFOUND siemens-dishwasher-014060394189002726`
Man benötigt mDNS oder einen lokalen DNS Eintrag für das Device auf die IP, sonst kann er nicht verbinden. Das erklärt die Frage nach der IP meines vorherigen Posts.
- Der https Port 443 muss in der Firewall zum Device geöffnet sein.

![grafik](https://github.com/eifel-tech/ioBroker.cloudless-homeconnect/assets/10372066/6b9fc056-5d87-4901-9636-627b7e88ad3a)

**Comment by eifel-tech** [comment]
Na, das ist ja mal eine positive Überraschung 👍

- Die Frage mit der IP hatte ich übersehen, sorry. Bei mir funktioniert das ohne mDNS direkt mit dem Domainnamen. Aber du könntest auch in `info.config` die Domain durch die lokale IP ersetzen, dann müsste es ja ohne mDNS gehen...
- dass der Port 443 geöffnet ist, bin ich direkt von ausgegangen.

Wenn du dir nun den Inhalt von `info.config` irgendwo sicherst, braucht der Adapter und das Gerät keine Internetverbindung mehr ;-)

**Comment by SaimenSays** [comment]
Ich gebe zu, ein etwas spezielles Setup. Der io-broker Rechner hat zwei Netzwerkschnittstellen. Das VLAN mit allen IOT-Geräten hat per default alles blockiert. So hab ich unter Kontrolle, wer da was mit wem kommuniziert ;)
Dann werde ich dem Geschirrspüler jetzt mal den Internetzugriff entziehen und sehen ob es funktionert...
