### ISSUE TITLE
Config parsen bei mehreren Geräten

### ISSUE THREAD

**Issue by Bongo2** [eifel-tech/ioBroker.cloudless-homeconnect#91]
Hi.

Ich habe den Adapter über die Katze installiert. Ich finde aber keine Instanz. In den Objekten gibt es unter cloudless-homeconnect nur einen leeren admin-Ordner.

Was ist das Problem?

In ./files/cloudless-homeconnect.admin/jsonConfig.json habe ich User und Passwort eingetragen. Im Protokoll gibt es keine Einträge zum Adapter.

Habe Backofen, Geschirrspüler und Kaffeemaschine in der App registriert.

Edit:
Ich weiß nicht ob wichtig ist. ioBroker läuft im Docker auf einer Synology.

Gruß
Bongo

**Comment by eifel-tech** [comment]
Hi,
meines Wissens ist es in iobroker normal, dass nur dann eine Instanz automatisch erzeugt wird, wenn der Adapter aus den offiziellen Repos installiert wird. Du musst also unter `Instanzen` nach der Installation des Adapters selbst eine anlegen.
Außerdem ist es glaub ich nicht gewollt, dass in irgendwelchen Dateien irgendetwas eingetragen wird. Username und Passwort muss in den Adaptereinstellungen der Instanz eingetragen werden. Das ist auch so üblich in iobroker ;-)

**Comment by Bongo2** [comment]
Danke für die Antwort.
Das ich in einer Datei was eingetragen habe, war nur aus verzweiflung, weil keine Instanz vorhanden war.

Ich habe den Adapter deinstalliert, installiert, Instanz erzeugt, User Passwort eingetragen.
Datenpunkte sind da ohne Werte.
Die config ist gefüllt.
Im Log steht:
`<html><body>

host.iobroker | 2024-08-25 17:20:13.567 | info | Restart adapter system.adapter.cloudless-homeconnect.0 because enabled
-- | -- | -- | --
host.iobroker | 2024-08-25 17:20:13.566 | error | instance system.adapter.cloudless-homeconnect.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
cloudless-homeconnect.0 | 2024-08-25 17:20:12.855 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
cloudless-homeconnect.0 | 2024-08-25 17:20:12.854 | info | terminating
cloudless-homeconnect.0 | 2024-08-25 17:20:12.849 | error | CryptoJs.Hmac256 is not a function
cloudless-homeconnect.0 | 2024-08-25 17:20:12.848 | error | TypeError: CryptoJs.Hmac256 is not a function     at new Socket (/opt/iobroker/node_modules/iobroker.cloudless-homeconnect/js/Socket.js:22:27)     at /opt/iobroker/node_modules/iobroker.cloudless-homeconnect/main.js:304:19     at Array.forEach (<anonymous>)     at CloudlessHomeconnect.connectDevices (/opt/iobroker/node_modules/iobroker.cloudless-homeconnect/main.js:303:34)     at CloudlessHomeconnect.onReady (/opt/iobroker/node_modules/iobroker.cloudless-homeconnect/main.js:109:8)
cloudless-homeconnect.0 | 2024-08-25 17:20:12.847 | error | unhandled promise rejection: CryptoJs.Hmac256 is not a function
cloudless-homeconnect.0 | 2024-08-25 17:20:12.846 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
cloudless-homeconnect.0 | 2024-08-25 17:20:07.659 | info | starting.  Version 1.0.4 (non-npm:  eifel-tech/ioBroker.cloudless-homeconnect#93c58e3ab4b1722a2292215f1a36c870f6d18557)  in /opt/iobroker/node_modules/iobroker.cloudless-homeconnect, node:  v20.16.0, js-controller: 6.0.9
host.iobroker | 2024-08-25 17:20:01.729 | info | instance  system.adapter.cloudless-homeconnect.0 in version "1.0.4" (non-npm:  eifel-tech/ioBroker.cloudless-homeconnect#93c58e3ab4b1722a2292215f1a36c870f6d18557)  started with pid 7892


</body>
</html>`

Was kann das noch sein?

**Comment by eifel-tech** [comment]
Welcher Hersteller ist dein Gerät? Das liegt vermutlich daran, dass ich das mangels Gerät nicht implementiert habe ;-) mein Ofen kommuniziert über Port 443, deiner anscheinend über Port 80. 
Ich bräuchte bitte den Inhalt des Datenpunktes `info.config` und würde mich dann an einer Implementierung versuchen. Allerdings ohne Garantie auf Erfolg. Siehe auch #78 ganz unten.

**Comment by eifel-tech** [comment]
Danke, die ist ziemlich lang und sieht auch nicht ganz richtig aus. Kannst du mir die XML-Dateien, die in `/opt/iobroker/iobroker-data/cloudless-homeconnect.0` liegen, schicken? Du bist der erste, der mehrere Geräte hat, vermutlich ist da beim Parsen noch irgendwas falsch.

**Comment by Bongo2** [comment]
Hier die XML-Dateien:
[cloudless-homeconnect.0.zip](https://github.com/user-attachments/files/16748283/cloudless-homeconnect.0.zip)

Vielen Dank.

**Comment by eifel-tech** [comment]
Besten Dank. Ich habe das Parsen der Konfiguration mal etwas überarbeitet. Gerade bei mehreren Geräten wurden immer die Eigenschaften aller Geräte in die Konfig geschrieben, das hat die so vergrößert. Bitte nochmal die Instanz und den Adapter löschen, evtl. auch die Objekte des Adapters und alles nochmal von vorn. Der Inhalt von `info.config` sollte nun deutlich kleiner sein. Den Inhalt dann bitte nochmal schicken, damit ich mich dem anderen Problem widmen kann. Danke :-)

**Comment by Bongo2** [comment]
Hab alles so gemacht. Die Version in der Instanz zeigt 1.1.0.
Hier die Dateien:
[config.json](https://github.com/user-attachments/files/16749956/config.json)
[cloudless-homeconnect.0(1).zip](https://github.com/user-attachments/files/16749958/cloudless-homeconnect.0.1.zip)

**Comment by eifel-tech** [comment]
Sieht doch gut aus jetzt :-)

**Comment by Bongo2** [comment]
Was sieht gut aus?

Bekomme immer noch die Meldungen:

`<html><body>

host.iobroker | 2024-08-26 17:02:59.290 | info | Restart adapter system.adapter.cloudless-homeconnect.0 because enabled
-- | -- | -- | --
host.iobroker | 2024-08-26 17:02:59.290 | error | instance system.adapter.cloudless-homeconnect.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
cloudless-homeconnect.0 | 2024-08-26 17:02:59.097 | info | terminating
cloudless-homeconnect.0 | 2024-08-26 17:02:58.595 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
cloudless-homeconnect.0 | 2024-08-26 17:02:58.593 | info | terminating
cloudless-homeconnect.0 | 2024-08-26 17:02:58.560 | error | CryptoJs.Hmac256 is not a function
cloudless-homeconnect.0 | 2024-08-26 17:02:58.559 | error | TypeError:  CryptoJs.Hmac256 is not a function    at new Socket  (/opt/iobroker/node_modules/iobroker.cloudless-homeconnect/js/Socket.js:22:27)     at  /opt/iobroker/node_modules/iobroker.cloudless-homeconnect/main.js:304:19     at Array.forEach (<anonymous>)    at  CloudlessHomeconnect.connectDevices  (/opt/iobroker/node_modules/iobroker.cloudless-homeconnect/main.js:303:34)     at CloudlessHomeconnect.onReady  (/opt/iobroker/node_modules/iobroker.cloudless-homeconnect/main.js:109:8)
cloudless-homeconnect.0 | 2024-08-26 17:02:58.557 | error | unhandled promise rejection: CryptoJs.Hmac256 is not a function
cloudless-homeconnect.0 | 2024-08-26 17:02:58.556 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
cloudless-homeconnect.0 | 2024-08-26 17:02:53.350 | info | starting.  Version 1.1.0 (non-npm:  eifel-tech/ioBroker.cloudless-homeconnect#6a96a43c7e6f4277e3ac60d3dce5d89334a87721)  in /opt/iobroker/node_modules/iobroker.cloudless-homeconnect, node:  v20.16.0, js-controller: 6.0.9
host.iobroker | 2024-08-26 17:02:48.716 | info | instance  system.adapter.cloudless-homeconnect.0 in version "1.1.0" (non-npm:  eifel-tech/ioBroker.cloudless-homeconnect#6a96a43c7e6f4277e3ac60d3dce5d89334a87721)  started with pid 5169
host.iobroker | 2024-08-26 17:02:47.367 | info | "system.adapter.cloudless-homeconnect.0" enabled


</body>
</html>`

**Comment by Bongo2** [comment]
@eifel-tech 
Hi, ich bekomme immer noch die Fehlermeldung. Das Besondere scheint zu sein, dass ich mehrere Geräte habe.
Bist du da noch dran? Hast du was raus finden können?

**Comment by Bongo2** [comment]
Obwohl ich schon Version 1.1.0 drauf hatte, habe ich nochmal über die Katze installiert. Und tatsächlich, keine Fehlermeldung mehr beim Starten der Instanz. Aber wie du schon gesagt hast, es stehen keine Werte in den Datenpunkten. Oder muss ich die Objekte vorher löschen?

Verstehe natürlich, wenn es noch andere wichtige Dinge gibt. Aber es wäre schon geil, wenn das funktionieren würde. Wenn ich was Testen soll oder du noch ein Log benötigst, stehe ich bereit.

**Comment by Bongo2** [comment]
Ich habe jetzt doch nochmal die Objekte gelöscht und die Instanz neu gestartet. Vorher war in jedem Datenpunkt Null gestanden. Jetzt steht zumindest mal was drin:
![grafik](https://github.com/user-attachments/assets/55efe485-00c0-4e9a-8aad-ee0a2da663c2)

**Comment by Bongo2** [comment]
Noch eine Info. Seit heute Morgen bekomme ich diese Meldung:

![grafik](https://github.com/user-attachments/assets/868c5b82-b9b5-462e-b2b8-a00678d97644)

**Comment by eifel-tech** [comment]
Klar, wie ich sagte, die Kommunikation mit den Geräten funktioniert halt (noch) nicht. 
Würdest du bitte zu dem Thema im anderen offenen issue kommentieren? Dieser hier dreht sich um das Parsen der Config, und das funktioniert ja. Deswegen hatte ich hier auch geschlossen ;-)

**Comment by Bongo2** [comment]
Aha ok. Bei diesen? "Errors using to connect to Neff oven"
Neff oven hab ich zwar nicht aber vermutlich soll das ein allgemeiner issue sein. Oder soll ich einen neuen aufmachen? Kann ich auch in deutsch schreiben?

**Comment by eifel-tech** [comment]
Ja, genau da bitte. Hat mit Neff oder Siemens erstmal  nichts zu tun, bei dir und bei ihm sind es aber  vermutlich die gleichen Ursachen. Ich kann den Titel auch demnächst noch ändern... Ich muss aber wie gesagt wieder ein bisschen Zeit haben, das Ganze ist nicht trivial :-( 
Du musst da jetzt auch nicht rein schreiben, dass das bei dir auch nicht geht oder so, das weiß ich ja ;-) aber wenn du dir das abonnierst, bekommst du mit, wenn sich da was ändert und kannst bei dir nachschauen, ob bspw. das gleiche im Log steht, ob du eine neue Version installieren sollst etc. Und ich muss nicht alles doppelt schreiben ;-)
Und wenn, dann den Adapter im Debug Modus laufen lassen und Logausgaben bitte nicht als Bild. Danke dir.
